CREATE TABLE IF NOT EXISTS clues (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
description TEXT NOT NULL,
obtained TEXT DEFAULT 'F'
);

CREATE TABLE IF NOT EXISTS items (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
description TEXT NOT NULL, 
image_path TEXT NOT NULL,
obtained TEXT DEFAULT 'F'
);

CREATE TABLE IF NOT EXISTS puzzles (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
solved TEXT DEFAULT 'unsolved'
);

CREATE TABLE IF NOT EXISTS dialogue (
id INTEGER PRIMARY KEY AUTOINCREMENT,
show TEXT DEFAULT 'no',
dialoguecontent TEXT
);